
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT EQUALS FOR ID INCREASE LBRACE LESS_THAN_EQUAL LPAREN NUMBER OUT PRINTLN RBRACE RPAREN SEMICOLON SYSTEM SYSTEMprogram : stmtsstmts : stmt\n             | stmts stmtstmt : for_stmt\n            | system_out_printlnfor_stmt : FOR LPAREN ID EQUALS NUMBER SEMICOLON ID LESS_THAN_EQUAL NUMBER SEMICOLON ID INCREASE RPAREN LBRACE stmts RBRACEsystem_out_println : SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON'
    
_lr_action_items = {'FOR':([0,2,3,4,5,8,24,29,30,31,],[6,6,-2,-4,-5,-3,-7,6,6,-6,]),'SYSTEM':([0,2,3,4,5,8,24,29,30,31,],[7,7,-2,-4,-5,-3,-7,7,7,-6,]),'$end':([1,2,3,4,5,8,24,31,],[0,-1,-2,-4,-5,-3,-7,-6,]),'RBRACE':([3,4,5,8,24,30,31,],[-2,-4,-5,-3,-7,31,-6,]),'LPAREN':([6,16,],[9,18,]),'DOT':([7,12,],[10,14,]),'ID':([9,17,18,25,],[11,19,20,26,]),'OUT':([10,],[12,]),'EQUALS':([11,],[13,]),'NUMBER':([13,21,],[15,23,]),'PRINTLN':([14,],[16,]),'SEMICOLON':([15,22,23,],[17,24,25,]),'LESS_THAN_EQUAL':([19,],[21,]),'RPAREN':([20,27,],[22,28,]),'INCREASE':([26,],[27,]),'LBRACE':([28,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmts':([0,29,],[2,30,]),'stmt':([0,2,29,30,],[3,8,3,8,]),'for_stmt':([0,2,29,30,],[4,4,4,4,]),'system_out_println':([0,2,29,30,],[5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmts','program',1,'p_program','parser_js.py',24),
  ('stmts -> stmt','stmts',1,'p_stmts','parser_js.py',28),
  ('stmts -> stmts stmt','stmts',2,'p_stmts','parser_js.py',29),
  ('stmt -> for_stmt','stmt',1,'p_stmt','parser_js.py',36),
  ('stmt -> system_out_println','stmt',1,'p_stmt','parser_js.py',37),
  ('for_stmt -> FOR LPAREN ID EQUALS NUMBER SEMICOLON ID LESS_THAN_EQUAL NUMBER SEMICOLON ID INCREASE RPAREN LBRACE stmts RBRACE','for_stmt',16,'p_for_stmt','parser_js.py',41),
  ('system_out_println -> SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON','system_out_println',9,'p_system_out_println','parser_js.py',47),
]
